# Generated by Django 3.2.5 on 2021-07-07 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
